version: '3.8'

services:
  fot_federated:
    image: cldjunior/fot_federated:1.0 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fot_federated
    volumes:
      - .:/fot_federated
    working_dir: /fot_federated
    hostname: fot_federated
    networks:
      fot-net:
        ipv4_address: 172.27.27.20
    environment:
      - TZ=America/Bahia
    stdin_open: true
    tty: true
    entrypoint: bash start_fl.sh
    mem_limit: 4g
    deploy:
      resources:
        limits:
          memory: 4G
networks:
  fot-net:
    external: true

